/** Catalogo base de ejercicios sembrado en el primer arranque. Ver DATA_MODEL.md. */
export const BUILT_IN_EXERCISES: Array<{ name: string; muscleGroup: string }> = [
  // Pecho
  { name: 'Press banca', muscleGroup: 'Pecho' },
  { name: 'Press inclinado con barra', muscleGroup: 'Pecho' },
  { name: 'Press inclinado con mancuernas', muscleGroup: 'Pecho' },
  { name: 'Press plano con mancuernas', muscleGroup: 'Pecho' },
  { name: 'Aperturas en polea', muscleGroup: 'Pecho' },
  { name: 'Aperturas en máquina', muscleGroup: 'Pecho' },
  { name: 'Fondos en paralelas', muscleGroup: 'Pecho' },
  { name: 'Press en máquina', muscleGroup: 'Pecho' },
  // Espalda
  { name: 'Dominadas', muscleGroup: 'Espalda' },
  { name: 'Jalón al pecho', muscleGroup: 'Espalda' },
  { name: 'Jalón agarre neutro', muscleGroup: 'Espalda' },
  { name: 'Remo con barra', muscleGroup: 'Espalda' },
  { name: 'Remo con mancuerna', muscleGroup: 'Espalda' },
  { name: 'Remo en máquina', muscleGroup: 'Espalda' },
  { name: 'Remo en polea baja', muscleGroup: 'Espalda' },
  { name: 'Pullover en polea', muscleGroup: 'Espalda' },
  { name: 'Face pull', muscleGroup: 'Espalda' },
  // Hombro
  { name: 'Press militar con barra', muscleGroup: 'Hombro' },
  { name: 'Press militar con mancuernas', muscleGroup: 'Hombro' },
  { name: 'Elevaciones laterales', muscleGroup: 'Hombro' },
  { name: 'Elevaciones laterales en polea', muscleGroup: 'Hombro' },
  { name: 'Elevaciones frontales', muscleGroup: 'Hombro' },
  { name: 'Pájaros', muscleGroup: 'Hombro' },
  { name: 'Press Arnold', muscleGroup: 'Hombro' },
  // Biceps
  { name: 'Curl con barra', muscleGroup: 'Bíceps' },
  { name: 'Curl con mancuernas', muscleGroup: 'Bíceps' },
  { name: 'Curl martillo', muscleGroup: 'Bíceps' },
  { name: 'Curl inclinado', muscleGroup: 'Bíceps' },
  { name: 'Curl predicador', muscleGroup: 'Bíceps' },
  { name: 'Curl en polea', muscleGroup: 'Bíceps' },
  // Triceps
  { name: 'Extensiones en polea', muscleGroup: 'Tríceps' },
  { name: 'Extensiones tras nuca', muscleGroup: 'Tríceps' },
  { name: 'Press francés', muscleGroup: 'Tríceps' },
  { name: 'Fondos en banco', muscleGroup: 'Tríceps' },
  { name: 'Patada de tríceps', muscleGroup: 'Tríceps' },
  // Pierna
  { name: 'Sentadilla', muscleGroup: 'Pierna' },
  { name: 'Sentadilla frontal', muscleGroup: 'Pierna' },
  { name: 'Prensa', muscleGroup: 'Pierna' },
  { name: 'Hack squat', muscleGroup: 'Pierna' },
  { name: 'Zancadas', muscleGroup: 'Pierna' },
  { name: 'Búlgaras', muscleGroup: 'Pierna' },
  { name: 'Peso muerto', muscleGroup: 'Pierna' },
  { name: 'Peso muerto rumano', muscleGroup: 'Pierna' },
  { name: 'Curl femoral tumbado', muscleGroup: 'Pierna' },
  { name: 'Curl femoral sentado', muscleGroup: 'Pierna' },
  { name: 'Extensiones de cuádriceps', muscleGroup: 'Pierna' },
  { name: 'Hip thrust', muscleGroup: 'Pierna' },
  { name: 'Abductores', muscleGroup: 'Pierna' },
  { name: 'Aductores', muscleGroup: 'Pierna' },
  { name: 'Gemelo de pie', muscleGroup: 'Pierna' },
  { name: 'Gemelo sentado', muscleGroup: 'Pierna' },
  // Core
  { name: 'Plancha', muscleGroup: 'Core' },
  { name: 'Elevaciones de piernas', muscleGroup: 'Core' },
  { name: 'Rueda abdominal', muscleGroup: 'Core' },
  { name: 'Crunch en polea', muscleGroup: 'Core' },
]
